//* ************ operation ***************** */
/*let value=3
let negvalue=-value
console.log(negvalue);*/
/*console.log(2+2);
console.log(3-2);
console.log(3*2);
console.log(3/2);
/*let str1="hello"
let str2=" world"

 let str3=str1 + str2
 console.log(str3); */


 /*console.log("1"+"3");
console.log(1+ "3");
console.log("1"+2+2);
console.log(1+2+"2");*/


 //console.log(+true);
 //console.log(+"");

 //let gamecounter=110//postfix
 //gamecounter++;
 //console.log(gamecounter);

 
 let gamecounter=110//pretfix
 ++gamecounter
 console.log(gamecounter);
 
 
 
 


